---
app_repo_url: "https://github.com/Godwin-T/DevOps-Stage-6.git"
app_repo_version: "main"
app_path: "/opt/devops-stage6"
app_user: "ubuntu"
base_domain: "your-domain.com"
api_base_path: "/api"
auth_api_prefix: "{{ api_base_path }}/auth"
todos_api_prefix: "{{ api_base_path }}/todos"
users_api_prefix: "{{ api_base_path }}/users"
zipkin_api_prefix: "{{ api_base_path }}/zipkin"
auth_service_base: "/auth"
todos_service_base: "/todos"
users_service_base: "/users"
traefik_acme_email: "admin@your-domain.com"
zipkin_subdomain: "zipkin"
